apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
  labels:
    app: producer-service
    component: analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer
        image: analytics-platform/producer:latest
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: GRPC_PORT
          value: "50051"
        - name: HTTP_PORT
          value: "8081"
        - name: LOG_LEVEL
          value: "info"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: producer-service
  type: LoadBalancer 